version: 0.2

phases:
  install:
    commands:
      - yum install java-11-amazon-corretto-devel.x86_64 -y
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
      - mvn clean 
  build:
    commands:
      - echo Build started on `date`
      - mvn install -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    #- target/Devops-1.0.0.war
    - '**/*'
